### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by stephme** [CuistotduCoin/cuistot#36]
Using MongoPay

**Comment by romainquellec** [comment]
- [ ] Table monochamp jsonb
- [ ] Ajout dans l'API graphQL (Mutation, Query)
- [ ] Ajouter Lambda correspondantes dans le handler
- [ ] Definir Workflow dans MangoPay
